### ISSUE TITLE
http://tokipona.net/parser/ is down

### ISSUE THREAD

**Issue by BackwardSpy** [matthewdeanmartin/tokipona.parser#37]
toki!

Attempting to visit the site results in an HTTP 503 error.

Thanks for your work on this tool so far, it's been useful to me as somebody learning to speak toki pona.

**Comment by matthewdeanmartin** [comment]
Sorry, it ran out of drive space. Cleaned it up & rebooted.

I'm glad someone is getting some use out of it!

**Comment by BackwardSpy** [comment]
I forgot to subscribe to the issue, and thus didn't see your comment. Thank you for bringing it back!
